### ISSUE TITLE
Remove Links to download the mobile app everywhere!

### ISSUE THREAD

**Issue by jainaayush01** [praveenscience/easya-website#17]
![image](https://user-images.githubusercontent.com/54480934/119803804-6aa2f580-befd-11eb-8952-e3588d8e4994.png)
Link to download mobile app is not given.
I think here we can target this to the end of the website where the download App option is available or we can add both the components for ios and android above
Share your thoughts

**Comment by praveenscience** [comment]
But we don't have a mobile app right now. Do you think it's feasible to make an app within 5 days and deploy it in stores? 🤔

**Comment by jainaayush01** [comment]
I don't think so but i clicked at the bottom of the page and it redirected me here:
https://play.google.com/store/apps/details?id=io.easya.easya
is it not the mobile app link?
![image](https://user-images.githubusercontent.com/54480934/119810264-814c4b00-bf03-11eb-999f-a47b4a231351.png)


Or is this the case: The client asked for the website and you have made it and they already had the mobile app? then we should remove the App link from below.

**Comment by praveenscience** [comment]
Yes, we have to remove that stuff right away! Can you please remove the links? Just make them dummy! 😅

**Comment by jainaayush01** [comment]
Ok on it
