### ISSUE TITLE
Custom Scrollbar

### ISSUE THREAD

**Issue by Saatvik21** [praveenscience/easya-website#21]
I would like to add a custom scrollbar that matches the colour of the website. 
Please assign this to me.

**Comment by praveenscience** [comment]
What about compatibility with the other systems? Like Internet Explorer and Mobile devices?

**Comment by Saatvik21** [comment]
I'll check it for internet explorer as well.
And for mobile devices, I don't think there should be a scrollbar for mobile devices like people will just swipe to go down rather than using the scrollbar.

**Comment by praveenscience** [comment]
Agreed, thanks. Start working on it... 🔥
