### ISSUE TITLE
Resetting and styling for more vibrant look 

### ISSUE THREAD

**Issue by nancyyadav22** [praveenscience/easya-website#22]
According to me the font size and styling of the written content can be better at many parts like testimonials, meet our team part etc.
I would like to give the webpages better look by focusing on *"styling written contents and backgrounds"*.
**kindly assign it to me**.

**Comment by praveenscience** [comment]
@nancyyadav22 Make sure you do it across all the pages and it should be consistent! Thanks! It's yours! 🔥

**Comment by nancyyadav22** [comment]
yeah sure sir!
