### ISSUE TITLE
Rename .env from the Codebase

### ISSUE THREAD

**Issue by jainaayush01** [praveenscience/easya-website#23]
I think it is of no use but still, it is not a good practice to keep an .env file in the codebase

**Comment by praveenscience** [comment]
Maybe can you just make it from `.env` to `.env.sample`? What say? For new people. And also add `.env` to the `.gitignore` file.

**Comment by jainaayush01** [comment]
Yeah sure that would be a nice idea.
Changes:
rename .env to .env.sample
add it to gitignore

am I correct?

**Comment by praveenscience** [comment]
Yes, you wanna do it or give another person a chance? Your wish!

**Comment by jainaayush01** [comment]
.env.sample will look like:

REACT_APP_LANG=<YOUR_NAME>

i did it already maybe in next one

**Comment by praveenscience** [comment]
I am gonna kill you! 🤣  It should be English! 🤦🏻‍♂️

**Comment by praveenscience** [comment]
@jainaayush01 Go for it...

- Rename...
- Add to GitIgnore...
- Sample should be English...

But check with the code, if English is what we're using.

**Comment by jainaayush01** [comment]
In the codebase, i saw the name of the contributor nikhar. so I thought that the variable is storing name of the person.

Changing it now.
