### ISSUE TITLE
Need new logos for this website!

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/easya-website#27]
Shall we revamp the site with a different logo? Up for grabs. 🔥

**Comment by ArchishmanSengupta** [comment]
Can i work on this @praveenscience ?

**Comment by praveenscience** [comment]
@ArchishmanSengupta Please go ahead... 🔥

**Comment by ArchishmanSengupta** [comment]
what type of logo is in your mind? should it be similar to an owl? Give me a brief @praveenscience

**Comment by praveenscience** [comment]
@ArchishmanSengupta Just make it as creative as possible. Something related to education... Need both logo and logotype! 🔥

**Comment by ArchishmanSengupta** [comment]
so since the website is more inclined to mathematics. I am trying to make something related to maths. is that ok?

**Comment by praveenscience** [comment]
Let's change the theme to coding! 💻

**Comment by dishiita** [comment]
Can I also work on this?

**Comment by praveenscience** [comment]
@dishiita Yes, more the better. Please do... 🔥

**Comment by dishiita** [comment]
Sir, I have made this logo. This is the first attempt. Could you please give feedback so I can improve
![logo](https://user-images.githubusercontent.com/54388663/120166962-cda4cd00-c21a-11eb-8c29-ecedd3ca509c.png)

**Comment by praveenscience** [comment]
@dishiita Looks really nice dude... Just create a PR with the logo... 😊  Quick.

**Comment by dishiita** [comment]
Ok sir, I have created a pull request with the logo. Let me know if anything is to be updated
