### ISSUE TITLE
Button Text not visible.

### ISSUE THREAD

**Issue by ArchishmanSengupta** [praveenscience/easya-website#31]
In landing page, 
the class Action-button's text to #how-it-works page is not visible. 
Reference: 
![is](https://user-images.githubusercontent.com/71402528/119848827-c1bebf80-bf29-11eb-80ca-679fd25db064.png)

Can you assign me this? 
Thank you

**Comment by praveenscience** [comment]
Wasn't this already been raised?

**Comment by praveenscience** [comment]
Dupe of #16!
