### ISSUE TITLE
Create login page

### ISSUE THREAD

**Issue by Maaz-Code** [praveenscience/easya-website#33]
I want to create a page to log in for the users. The page will not be functional but at least the login button will take you to a page to log in as now it just takes you to the home page. Also in mobile view, there is no login button so I would like to add that too.
@praveenscience Please assign me this task.

**Comment by praveenscience** [comment]
Sure, go for it. 😊

**Comment by anusha7530** [comment]
I want to work on this issue. Kindly assign me this issue as a part of GSSOC'24

**Comment by praveenscience** [comment]
@anusha7530 Go for it! 💯

**Comment by praveenscience** [comment]
@Maaz-Code don't you think what you did and not inform is not ethical?

**Comment by anusha7530** [comment]
@praveenscience What credentials do you want from the user to register to your platform?
