### ISSUE TITLE
Make the Website Responsive and Add some Transitions 

### ISSUE THREAD

**Issue by hariketsheth** [praveenscience/easya-website#44]
I wanted to suggest that if we can make the website responsive since some of the buttons and the text was just not going properly on some devices. So this could be rectified if you just make it responsive. 
Secondly, You should consider adding a **smooth transition** when a user clicks on the "Login", "Pricing" and "Blog" buttons.

**Comment by praveenscience** [comment]
Cool. If you wanna take it up, go for it... 🔥
