### ISSUE TITLE
add some badges to the README file

### ISSUE THREAD

**Issue by Umesh-01** [praveenscience/easya-website#47]
## Description
add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

## Describe the solution you'd like

![image](https://user-images.githubusercontent.com/83420185/124011866-1a3c1d80-d9fe-11eb-923a-00c6d9a08379.png)

I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

### Work under/as

- [x] LGMSOC
- [ ] Contributor

**Comment by Umesh-01** [comment]
@praveenscience sir should I work on this issue??

**Comment by praveenscience** [comment]
@Umesh-01 Cool man, go for it. 😊
