### ISSUE TITLE
Transition on scroll 

### ISSUE THREAD

**Issue by rajbir21-droid** [praveenscience/easya-website#49]
I want to add some transition to all the components when the user scroll and also some animation to the scroll to top button ,it will be visible only when the user scroll down

**Comment by rajbir21-droid** [comment]
@praveenscience can I work on this issue?

**Comment by rajbir21-droid** [comment]
https://user-images.githubusercontent.com/64858573/127530451-561ebb94-d118-4b02-83c2-d09fd2b122a4.mp4

**Comment by rajbir21-droid** [comment]
@praveenscience please have a look

**Comment by praveenscience** [comment]
Thanks added it but we won't be deploying this in the main website because this looks cool, but too unprofessional. But thanks for your work. 😁

Your PR is accepted. Are you a part of any Open Source programme?

**Comment by rajbir21-droid** [comment]
Yes, LGMSOC 21
